services:
  nginx:
    build:
      context: ./nginx
    image: memorizor/nginx
    ports:
      - '80:80'
    depends_on:
      - account
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  account:
    build:
      context: ./services/account
      target: compiler
    image: memorizor/services-account-src
    env_file: ./.env.dev
    expose:
      - 8080
    volumes:
      - ./services/account/:/src
      - ./keys/:/keys
    depends_on:
      - postgres-users
    command: reflex -r "\.go$$" -s -- sh -c "go run ."

  postgres-users:
    image: 'postgres:latest'
    env_file: ./.env.dev
    ports:
      - '5433:5432'
    volumes:
      - ./data/users/:/var/lib/postgresql/data/
    command: ['postgres', '-c', 'log_statement=all']
