services:
  nginx:
    build:
      context: ./nginx
    image: memorizor/nginx
    ports:
      - '80:80'
    depends_on:
      - account
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/logs:/var/log/nginx/

  account:
    build:
      context: ./services/account
      target: compiler
    image: memorizor/services-account-src
    env_file: ./.env.dev
    expose:
      - 8080
    volumes:
      - ./services/account/:/src
      - ./keys/:/keys
    depends_on:
      - postgres-users
      - redis-tokens
    command: reflex -r "\.go$$" -s -- sh -c "go run ."

  postgres-users:
    image: 'postgres:latest'
    env_file: ./.env.dev
    ports:
      - '5433:5432'
    volumes:
      - ./data/users/:/var/lib/postgresql/data/
    command: ['postgres', '-c', 'log_statement=all']

  redis-tokens:
    image: 'redis:latest'
    env_file: ./.env.dev
    ports:
      - '6379:6379'
    volumes:
      - ./data/tokens/:/data/

  client:
    build:
      context: ./client
      target: build
    image: memorizor/client-src
    env_file: ./.env.dev
    expose:
      - 80
    volumes:
      - ./client/:/app
    depends_on:
      - account
      - postgres-users
      - redis-tokens
    command: pnpm run dev --host client --port 80
